/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-13 09:15:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<a name='TSA_57'></a>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("	.utilWrap {width: 100%;}\r\n");
      out.write("	.utilWrap .utilBox {width: 100%;height: 40px; line-height: 40px; max-width: 1280px; margin:0 auto;}\r\n");
      out.write("	.utilWrap .utilBox .util {float: right;}\r\n");
      out.write("	.utilWrap .utilBox .util ul {display:flex;}\r\n");
      out.write("	.utilWrap .utilBox .util ul li {}\r\n");
      out.write("	.utilWrap .utilBox .util ul li a{padding:0 10px; font-weight: 500; font-size: 13px; color: #a7a9ac; position: relative; transition: 0.2s ease;}\r\n");
      out.write("	.utilWrap .utilBox .util ul li a:hover{color: #87553d;}\r\n");
      out.write("	.utilWrap .utilBox .util ul li a:after {content: \"\"; display: block; position: absolute; width: 1px; height: 10px; left: 0; top: 5px; background-color: #a7a9ac;}\r\n");
      out.write("	.utilWrap .utilBox .util ul li:nth-child(1) a:after {display:none;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div id=\"layer_pop_cls\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"utilWrap\">\r\n");
      out.write("	<div class=\"utilBox\">\r\n");
      out.write("	<!-- 	<a href=\"#\" id=\"favorite\" class=\"addSite\"><span class=\"iconfont ftic-Favorites\"></span> 즐겨찾기</a> -->\r\n");
      out.write("		<div class=\"util tmb_logout  hide\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"javascript:;\" class=\"join_pop_cls\">회원가입</a></li>\r\n");
      out.write("				<li><a href=\"/member/login.asp\">로그인</a></li>\r\n");
      out.write("				<li><a href=\"/my/order_total.asp?mode=deliver\">주문배송조회</a></li>\r\n");
      out.write("				<li><a href=\"/cscenter/\">고객센터</a></li>\r\n");
      out.write("			</ul>		\r\n");
      out.write("			<!-- \r\n");
      out.write("			<span href=\"/cscenter/main.asp\" class=\"inList\"> -->\r\n");
      out.write("<!-- 			</span> -->\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"util tmb_login tmb_login\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.user }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<li><a href=\"javascript:;\" class=\"join_pop_cls\">회원가입</a></li>\r\n");
      out.write("					<li><a href=\"/member/login.asp\">로그인</a></li>\r\n");
      out.write("				</c:if>\r\n");
      out.write("				<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<li><a href=\"/my\" class=\"hi\">반갑습니다. ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님</a></li>\r\n");
      out.write("					<li><a href=\"/logout.asp\">로그아웃</a></li>\r\n");
      out.write("				</c:if>\r\n");
      out.write("					\r\n");
      out.write("				<li><a href=\"/my/order_total.asp?mode=deliver\">주문배송조회</a></li>\r\n");
      out.write("				<li><a href=\"/cscenter/\">고객센터</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$.ajax({\r\n");
      out.write("	type:\"post\",\r\n");
      out.write("	url:\"/common/ajax/exec_getCartCnt.asp\",\r\n");
      out.write("	success:function(data, state, xhr){\r\n");
      out.write("		$(\".cartCnt\").each(function(){$(this).html(data);});\r\n");
      out.write("	}\r\n");
      out.write("})\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	$(\".join_pop_cls\").click(function(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			url:\"/common/ajax/exec_NewMainTopMenu.asp\",\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				$(\"#layer_pop_cls\").html(data);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script><script>$('.tmb_login.hide, .tmb_logout.hide').remove();</script></div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
